name: Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  workflow:
    permissions:
      contents: write
    uses: quike/workflow-github/.github/workflows/release.yml@v1
    secrets: inherit
