name: Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  workflow:
    permissions:
      contents: write
    uses: quike/workflow-github/.github/workflows/release.yml@v1.0.3
    secrets: inherit
